// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse(
    {Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Role for an OOB token. Encoded into byte 0 of the token blob.
enum UwbRole {
  controller,
  controlee,
}

/// Stable error code surface for the [RangingError] raised from a UWB
/// session. The native sides map their respective platform errors
/// (`RangingResultFailure.reasonCode` / `STATE_CHANGE_REASON_*` on
/// Android; `NIError.Code` / `CBError.Code` on iOS) onto these values.
enum UwbErrorCode {
  /// The OS denied a permission the plugin needs (Bluetooth scan/connect/
  /// advertise, fine location on Android < 12, Nearby Interaction or camera
  /// usage on iOS). Recover by requesting the missing permission and
  /// retrying — the rest of the plugin state is unchanged.
  permissionDenied,

  /// The UWB radio is present but disabled or unavailable (airplane mode,
  /// hardware fault, OS-level toggle). Surface a "turn UWB on" prompt to
  /// the user; nothing the plugin can do programmatically.
  uwbDisabled,

  /// The peer dropped during ranging (out of range, BLE link lost, app on
  /// the other side closed). The session is torn down before this fires;
  /// the only recovery is rediscovery and re-pair.
  peerLost,

  /// UWB use is restricted in the device's current region (Russia,
  /// Indonesia, and a small number of other jurisdictions disable the
  /// radio entirely). Not user-recoverable; surface a region-restriction
  /// notice.
  regionalRestriction,

  /// The platform refused to start the UWB session (invalid token,
  /// channel/preamble mismatch, unsupported config). Usually indicates the
  /// peers disagreed on session parameters; re-pair before retrying.
  sessionInitFailed,

  /// The OOB transport (BLE GATT) failed during a critical exchange —
  /// connection drop mid-handshake, characteristic write failure, GATT
  /// timeout. Retry the operation; if it persists, BLE on one side is in
  /// a bad state.
  transportError,

  /// Catch-all for platform errors the plugin couldn't classify. The
  /// `message` field on [RangingError] / [UwbException] carries the
  /// underlying platform string for debugging.
  unknown,
}

class UwbDevice {
  UwbDevice({
    required this.id,
    required this.name,
    required this.platform,
  });

  String id;

  String name;

  String platform;

  Object encode() {
    return <Object?>[
      id,
      name,
      platform,
    ];
  }

  static UwbDevice decode(Object result) {
    result as List<Object?>;
    return UwbDevice(
      id: result[0]! as String,
      name: result[1]! as String,
      platform: result[2]! as String,
    );
  }
}

/// BLE service + characteristic triplet describing an accessory.
///
/// `serviceUuid` is the GATT service the iPhone/Android scans for and
/// connects to. `rxUuid` is the characteristic the host writes to (the
/// accessory's "Rx"); `txUuid` is the one the accessory pushes via
/// notifications (its "Tx").
///
/// `vendorTag` is appended to `UwbDevice.platform` as `accessory:<tag>` so
/// the Dart side can filter; pass `null` for the built-in Apple-FiRa
/// handling (`UwbDevice.platform == "accessory"`).
class AccessoryProfile {
  AccessoryProfile({
    required this.serviceUuid,
    required this.rxUuid,
    required this.txUuid,
    this.vendorTag,
  });

  String serviceUuid;

  String rxUuid;

  String txUuid;

  String? vendorTag;

  Object encode() {
    return <Object?>[
      serviceUuid,
      rxUuid,
      txUuid,
      vendorTag,
    ];
  }

  static AccessoryProfile decode(Object result) {
    result as List<Object?>;
    return AccessoryProfile(
      serviceUuid: result[0]! as String,
      rxUuid: result[1]! as String,
      txUuid: result[2]! as String,
      vendorTag: result[3] as String?,
    );
  }
}

class TokenPayload {
  TokenPayload({
    required this.bytes,
  });

  Uint8List bytes;

  Object encode() {
    return <Object?>[
      bytes,
    ];
  }

  static TokenPayload decode(Object result) {
    result as List<Object?>;
    return TokenPayload(
      bytes: result[0]! as Uint8List,
    );
  }
}

class VoidResult {
  VoidResult({
    required this.ok,
    this.error,
  });

  bool ok;

  String? error;

  Object encode() {
    return <Object?>[
      ok,
      error,
    ];
  }

  static VoidResult decode(Object result) {
    result as List<Object?>;
    return VoidResult(
      ok: result[0]! as bool,
      error: result[1] as String?,
    );
  }
}

/// Error raised from a UWB session.
class RangingError {
  RangingError({
    required this.code,
    required this.message,
  });

  UwbErrorCode code;

  String message;

  Object encode() {
    return <Object?>[
      code.index,
      message,
    ];
  }

  static RangingError decode(Object result) {
    result as List<Object?>;
    return RangingError(
      code: UwbErrorCode.values[result[0]! as int],
      message: result[1]! as String,
    );
  }
}

/// Options modulating a ranging session. iOS-only flags are no-ops on
/// Android.
class RangingOptions {
  RangingOptions({
    this.cameraAssist = false,
    this.extendedDistance = false,
  });

  /// iOS only. Enables `NINearbyPeerConfiguration.isCameraAssistanceEnabled`.
  /// Requires `NSCameraUsageDescription` in the host app's Info.plist.
  bool cameraAssist;

  /// iOS 17.4+ accessory only. Enables
  /// `NINearbyAccessoryConfiguration.isExtendedDistanceMeasurementEnabled`.
  bool extendedDistance;

  Object encode() {
    return <Object?>[
      cameraAssist,
      extendedDistance,
    ];
  }

  static RangingOptions decode(Object result) {
    result as List<Object?>;
    return RangingOptions(
      cameraAssist: result[0]! as bool,
      extendedDistance: result[1]! as bool,
    );
  }
}

/// What the local UWB radio supports. Some fields are platform-specific:
/// the iOS-only flags are always `false` on Android, and the Android-only
/// ranging-stack details (channels, config IDs, AoA, min interval) are
/// always empty / zero on iOS.
class DeviceCapabilities {
  DeviceCapabilities({
    required this.supportsPreciseDistance,
    required this.supportsDirection,
    required this.supportsCameraAssist,
    required this.supportsExtendedDistance,
    required this.supportedChannels,
    required this.supportedConfigIds,
    this.minRangingIntervalMs,
    required this.supportsAoa,
  });

  bool supportsPreciseDistance;

  bool supportsDirection;

  bool supportsCameraAssist;

  bool supportsExtendedDistance;

  List<int?> supportedChannels;

  List<int?> supportedConfigIds;

  int? minRangingIntervalMs;

  bool supportsAoa;

  Object encode() {
    return <Object?>[
      supportsPreciseDistance,
      supportsDirection,
      supportsCameraAssist,
      supportsExtendedDistance,
      supportedChannels,
      supportedConfigIds,
      minRangingIntervalMs,
      supportsAoa,
    ];
  }

  static DeviceCapabilities decode(Object result) {
    result as List<Object?>;
    return DeviceCapabilities(
      supportsPreciseDistance: result[0]! as bool,
      supportsDirection: result[1]! as bool,
      supportsCameraAssist: result[2]! as bool,
      supportsExtendedDistance: result[3]! as bool,
      supportedChannels: (result[4] as List<Object?>?)!.cast<int?>(),
      supportedConfigIds: (result[5] as List<Object?>?)!.cast<int?>(),
      minRangingIntervalMs: result[6] as int?,
      supportsAoa: result[7]! as bool,
    );
  }
}

class RangingSample {
  RangingSample({
    required this.deviceId,
    required this.distanceMeters,
    this.azimuthDegrees,
    this.elevationDegrees,
    required this.elapsedRealtimeNanos,
  });

  String deviceId;

  double distanceMeters;

  double? azimuthDegrees;

  double? elevationDegrees;

  int elapsedRealtimeNanos;

  Object encode() {
    return <Object?>[
      deviceId,
      distanceMeters,
      azimuthDegrees,
      elevationDegrees,
      elapsedRealtimeNanos,
    ];
  }

  static RangingSample decode(Object result) {
    result as List<Object?>;
    return RangingSample(
      deviceId: result[0]! as String,
      distanceMeters: result[1]! as double,
      azimuthDegrees: result[2] as double?,
      elevationDegrees: result[3] as double?,
      elapsedRealtimeNanos: result[4]! as int,
    );
  }
}

class _UwbHostApiCodec extends StandardMessageCodec {
  const _UwbHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is AccessoryProfile) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is DeviceCapabilities) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RangingOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is TokenPayload) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is UwbDevice) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is VoidResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return AccessoryProfile.decode(readValue(buffer)!);
      case 129:
        return DeviceCapabilities.decode(readValue(buffer)!);
      case 130:
        return RangingOptions.decode(readValue(buffer)!);
      case 131:
        return TokenPayload.decode(readValue(buffer)!);
      case 132:
        return UwbDevice.decode(readValue(buffer)!);
      case 133:
        return VoidResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class UwbHostApi {
  /// Constructor for [UwbHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  UwbHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _UwbHostApiCodec();

  Future<VoidResult> startDiscovery(String localName) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.startDiscovery';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[localName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<VoidResult> stopDiscovery() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopDiscovery';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<List<UwbDevice?>> getDiscovered() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDiscovered';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as List<Object?>?)!.cast<UwbDevice?>();
    }
  }

  Future<VoidResult> acceptRequest(
      String deviceId, TokenPayload myToken) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.acceptRequest';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[deviceId, myToken]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<VoidResult> declineRequest(String deviceId) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.declineRequest';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[deviceId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<VoidResult> registerAccessoryProfile(AccessoryProfile profile) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.registerAccessoryProfile';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[profile]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<VoidResult> unregisterAccessoryProfile(String serviceUuid) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.unregisterAccessoryProfile';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[serviceUuid]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<TokenPayload> exchangeTokens(
      String deviceId, TokenPayload myToken) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.exchangeTokens';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[deviceId, myToken]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as TokenPayload?)!;
    }
  }

  Future<bool> isUwbAvailable() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.isUwbAvailable';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as bool?)!;
    }
  }

  /// Returns the platform-native OOB token to share with the peer.
  /// On Android the format is the 9-byte little-endian blob:
  ///   [0]   role (0=controller, 1=controlee)
  ///   [1..2] shortAddr (u16)
  ///   [3]   channel (u8, controller only)
  ///   [4]   preambleIndex (u8, controller only)
  ///   [5..8] sessionId (u32, controller only)
  /// On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
  Future<TokenPayload> getLocalToken(UwbRole role) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.getLocalToken';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[role.index]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as TokenPayload?)!;
    }
  }

  Future<VoidResult> startRanging(
      String deviceId, RangingOptions options) async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.startRanging';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList = await __pigeon_channel
        .send(<Object?>[deviceId, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  Future<VoidResult> stopRanging() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopRanging';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as VoidResult?)!;
    }
  }

  /// Snapshot of the local UWB radio's capabilities. Returns the
  /// platform-specific profile (iOS-only fields are false on Android,
  /// Android-only fields are empty on iOS).
  Future<DeviceCapabilities> getDeviceCapabilities() async {
    const String __pigeon_channelName =
        'dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDeviceCapabilities';
    final BasicMessageChannel<Object?> __pigeon_channel =
        BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as DeviceCapabilities?)!;
    }
  }
}

class _UwbFlutterApiCodec extends StandardMessageCodec {
  const _UwbFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is RangingError) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is RangingSample) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is TokenPayload) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is UwbDevice) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:
        return RangingError.decode(readValue(buffer)!);
      case 129:
        return RangingSample.decode(readValue(buffer)!);
      case 130:
        return TokenPayload.decode(readValue(buffer)!);
      case 131:
        return UwbDevice.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Callbacks from the host platform up to Dart.
abstract class UwbFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _UwbFlutterApiCodec();

  void onDeviceFound(UwbDevice device);

  void onDeviceLost(String deviceId);

  void onRangingSample(RangingSample sample);

  void onPeerLost(String deviceId);

  void onRangingError(String deviceId, RangingError error);

  void onIncomingRequest(UwbDevice device, TokenPayload peerToken);

  static void setup(UwbFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound was null, expected non-null UwbDevice.');
          try {
            api.onDeviceFound(arg_device!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost was null, expected non-null String.');
          try {
            api.onDeviceLost(arg_deviceId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final RangingSample? arg_sample = (args[0] as RangingSample?);
          assert(arg_sample != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample was null, expected non-null RangingSample.');
          try {
            api.onRangingSample(arg_sample!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost was null, expected non-null String.');
          try {
            api.onPeerLost(arg_deviceId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_deviceId = (args[0] as String?);
          assert(arg_deviceId != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError was null, expected non-null String.');
          final RangingError? arg_error = (args[1] as RangingError?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError was null, expected non-null RangingError.');
          try {
            api.onRangingError(arg_deviceId!, arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> __pigeon_channel =
          BasicMessageChannel<Object?>(
              'dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest',
              pigeonChannelCodec,
              binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final UwbDevice? arg_device = (args[0] as UwbDevice?);
          assert(arg_device != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest was null, expected non-null UwbDevice.');
          final TokenPayload? arg_peerToken = (args[1] as TokenPayload?);
          assert(arg_peerToken != null,
              'Argument for dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest was null, expected non-null TokenPayload.');
          try {
            api.onIncomingRequest(arg_device!, arg_peerToken!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
                error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
