// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Role for an OOB token. Encoded into byte 0 of the token blob.
enum UwbRole: Int {
  case controller = 0
  case controlee = 1
}

/// Stable error code surface for the [RangingError] raised from a UWB
/// session. The native sides map their respective platform errors
/// (`RangingResultFailure.reasonCode` / `STATE_CHANGE_REASON_*` on
/// Android; `NIError.Code` / `CBError.Code` on iOS) onto these values.
enum UwbErrorCode: Int {
  /// The OS denied a permission the plugin needs (Bluetooth scan/connect/
  /// advertise, fine location on Android < 12, Nearby Interaction or camera
  /// usage on iOS). Recover by requesting the missing permission and
  /// retrying — the rest of the plugin state is unchanged.
  case permissionDenied = 0
  /// The UWB radio is present but disabled or unavailable (airplane mode,
  /// hardware fault, OS-level toggle). Surface a "turn UWB on" prompt to
  /// the user; nothing the plugin can do programmatically.
  case uwbDisabled = 1
  /// The peer dropped during ranging (out of range, BLE link lost, app on
  /// the other side closed). The session is torn down before this fires;
  /// the only recovery is rediscovery and re-pair.
  case peerLost = 2
  /// UWB use is restricted in the device's current region (Russia,
  /// Indonesia, and a small number of other jurisdictions disable the
  /// radio entirely). Not user-recoverable; surface a region-restriction
  /// notice.
  case regionalRestriction = 3
  /// The platform refused to start the UWB session (invalid token,
  /// channel/preamble mismatch, unsupported config). Usually indicates the
  /// peers disagreed on session parameters; re-pair before retrying.
  case sessionInitFailed = 4
  /// The OOB transport (BLE GATT) failed during a critical exchange —
  /// connection drop mid-handshake, characteristic write failure, GATT
  /// timeout. Retry the operation; if it persists, BLE on one side is in
  /// a bad state.
  case transportError = 5
  /// Catch-all for platform errors the plugin couldn't classify. The
  /// `message` field on [RangingError] / [UwbException] carries the
  /// underlying platform string for debugging.
  case unknown = 6
}

/// Discriminator for [AccessoryHandshakeEvent.kind].
///
/// Pigeon doesn't support sealed unions, so [AccessoryHandshakeEvent] is
/// a flat struct with a [kind] code and optional [bytes]/[errorMessage]
/// fields populated per kind.
enum AccessoryHandshakeEventKind: Int {
  /// BLE connection ready, notifications subscribed. The adapter's
  /// `handshake` callback is dispatched right after this event.
  case connected = 0
  /// Inbound bytes from the accessory's notify characteristic.
  /// [AccessoryHandshakeEvent.bytes] carries the frame.
  case notifyBytes = 1
  /// Transport-level error (write failed, GATT timeout, etc.).
  /// [AccessoryHandshakeEvent.errorMessage] carries the platform message.
  case transportError = 2
  /// Peer disconnected. The adapter's pending Future fails with a
  /// transport error.
  case disconnected = 3
  /// `stopRanging` was called while the adapter was still running.
  /// The adapter should cancel its work and return.
  case stopRequested = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct UwbDevice {
  var id: String
  var name: String
  var platform: String

  static func fromList(_ list: [Any?]) -> UwbDevice? {
    let id = list[0] as! String
    let name = list[1] as! String
    let platform = list[2] as! String

    return UwbDevice(
      id: id,
      name: name,
      platform: platform
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      platform,
    ]
  }
}

/// BLE service + characteristic triplet describing an accessory.
///
/// `serviceUuid` is the GATT service the iPhone/Android scans for and
/// connects to. `rxUuid` is the characteristic the host writes to (the
/// accessory's "Rx"); `txUuid` is the one the accessory pushes via
/// notifications (its "Tx").
///
/// `vendorTag` is appended to `UwbDevice.platform` as `accessory:<tag>` so
/// the Dart side can filter; pass `null` for the built-in Apple-FiRa
/// handling (`UwbDevice.platform == "accessory"`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccessoryProfile {
  var serviceUuid: String
  var rxUuid: String
  var txUuid: String
  var vendorTag: String? = nil

  static func fromList(_ list: [Any?]) -> AccessoryProfile? {
    let serviceUuid = list[0] as! String
    let rxUuid = list[1] as! String
    let txUuid = list[2] as! String
    let vendorTag: String? = nilOrValue(list[3])

    return AccessoryProfile(
      serviceUuid: serviceUuid,
      rxUuid: rxUuid,
      txUuid: txUuid,
      vendorTag: vendorTag
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      rxUuid,
      txUuid,
      vendorTag,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenPayload {
  var bytes: FlutterStandardTypedData

  static func fromList(_ list: [Any?]) -> TokenPayload? {
    let bytes = list[0] as! FlutterStandardTypedData

    return TokenPayload(
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoidResult {
  var ok: Bool
  var error: String? = nil

  static func fromList(_ list: [Any?]) -> VoidResult? {
    let ok = list[0] as! Bool
    let error: String? = nilOrValue(list[1])

    return VoidResult(
      ok: ok,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      ok,
      error,
    ]
  }
}

/// Error raised from a UWB session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RangingError {
  var code: UwbErrorCode
  var message: String

  static func fromList(_ list: [Any?]) -> RangingError? {
    let code = UwbErrorCode(rawValue: list[0] as! Int)!
    let message = list[1] as! String

    return RangingError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code.rawValue,
      message,
    ]
  }
}

/// Options modulating a ranging session. iOS-only flags are no-ops on
/// Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RangingOptions {
  /// iOS only. Enables `NINearbyPeerConfiguration.isCameraAssistanceEnabled`.
  /// Requires `NSCameraUsageDescription` in the host app's Info.plist.
  var cameraAssist: Bool
  /// iOS 17.4+ accessory only. Enables
  /// `NINearbyAccessoryConfiguration.isExtendedDistanceMeasurementEnabled`.
  var extendedDistance: Bool

  static func fromList(_ list: [Any?]) -> RangingOptions? {
    let cameraAssist = list[0] as! Bool
    let extendedDistance = list[1] as! Bool

    return RangingOptions(
      cameraAssist: cameraAssist,
      extendedDistance: extendedDistance
    )
  }
  func toList() -> [Any?] {
    return [
      cameraAssist,
      extendedDistance,
    ]
  }
}

/// What the local UWB radio supports. Some fields are platform-specific:
/// the iOS-only flags are always `false` on Android, and the Android-only
/// ranging-stack details (channels, config IDs, AoA, min interval) are
/// always empty / zero on iOS.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DeviceCapabilities {
  var supportsPreciseDistance: Bool
  var supportsDirection: Bool
  var supportsCameraAssist: Bool
  var supportsExtendedDistance: Bool
  var supportedChannels: [Int64?]
  var supportedConfigIds: [Int64?]
  var minRangingIntervalMs: Int64? = nil
  var supportsAoa: Bool

  static func fromList(_ list: [Any?]) -> DeviceCapabilities? {
    let supportsPreciseDistance = list[0] as! Bool
    let supportsDirection = list[1] as! Bool
    let supportsCameraAssist = list[2] as! Bool
    let supportsExtendedDistance = list[3] as! Bool
    let supportedChannels = list[4] as! [Int64?]
    let supportedConfigIds = list[5] as! [Int64?]
    let minRangingIntervalMs: Int64? = isNullish(list[6]) ? nil : (list[6] is Int64? ? list[6] as! Int64? : Int64(list[6] as! Int32))
    let supportsAoa = list[7] as! Bool

    return DeviceCapabilities(
      supportsPreciseDistance: supportsPreciseDistance,
      supportsDirection: supportsDirection,
      supportsCameraAssist: supportsCameraAssist,
      supportsExtendedDistance: supportsExtendedDistance,
      supportedChannels: supportedChannels,
      supportedConfigIds: supportedConfigIds,
      minRangingIntervalMs: minRangingIntervalMs,
      supportsAoa: supportsAoa
    )
  }
  func toList() -> [Any?] {
    return [
      supportsPreciseDistance,
      supportsDirection,
      supportsCameraAssist,
      supportsExtendedDistance,
      supportedChannels,
      supportedConfigIds,
      minRangingIntervalMs,
      supportsAoa,
    ]
  }
}

/// Snapshot of everything the plugin needs to start ranging.
///
/// Returned by [UwbHostApi.checkReadiness]. The host app should branch
/// on each field and surface the appropriate UI:
///
/// ```dart
/// final r = await uwb.checkReadiness();
/// if (!r.bluetoothEnabled) promptEnableBluetooth();
/// else if (!r.permissionsGranted) requestPermissions(r.missingPermissions);
/// else if (!r.uwbAvailable) showUnsupportedScreen();
/// else readyToRange();
/// ```
///
/// Generated class from Pigeon that represents data sent in messages.
struct UwbReadiness {
  /// `true` if the device has a UWB radio and the OS allows ranging.
  /// Mirrors [UwbHostApi.isUwbAvailable] — false on the iOS simulator and
  /// on devices without UWB hardware.
  var uwbAvailable: Bool
  /// `true` if the system Bluetooth radio is powered on. Required for
  /// OOB discovery / pairing on both platforms.
  var bluetoothEnabled: Bool
  /// `true` if every runtime permission the plugin needs has been
  /// granted. Always `true` on iOS — iOS does not expose a programmatic
  /// pre-check for `NSBluetoothAlwaysUsageDescription` /
  /// `NSNearbyInteractionUsageDescription`; the OS prompts on first use.
  var permissionsGranted: Bool
  /// Android permission identifiers (`android.permission.*`) the plugin
  /// needs but the user has not granted yet. Empty on iOS. Pass these
  /// directly to your permission package — for example with
  /// `permission_handler`:
  ///
  /// ```dart
  /// final perms = r.missingPermissions
  ///     .map(Permission.byValue)
  ///     .toList();
  /// await perms.request();
  /// ```
  var missingPermissions: [String?]

  static func fromList(_ list: [Any?]) -> UwbReadiness? {
    let uwbAvailable = list[0] as! Bool
    let bluetoothEnabled = list[1] as! Bool
    let permissionsGranted = list[2] as! Bool
    let missingPermissions = list[3] as! [String?]

    return UwbReadiness(
      uwbAvailable: uwbAvailable,
      bluetoothEnabled: bluetoothEnabled,
      permissionsGranted: permissionsGranted,
      missingPermissions: missingPermissions
    )
  }
  func toList() -> [Any?] {
    return [
      uwbAvailable,
      bluetoothEnabled,
      permissionsGranted,
      missingPermissions,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RangingSample {
  var deviceId: String
  var distanceMeters: Double
  var azimuthDegrees: Double? = nil
  var elevationDegrees: Double? = nil
  var elapsedRealtimeNanos: Int64

  static func fromList(_ list: [Any?]) -> RangingSample? {
    let deviceId = list[0] as! String
    let distanceMeters = list[1] as! Double
    let azimuthDegrees: Double? = nilOrValue(list[2])
    let elevationDegrees: Double? = nilOrValue(list[3])
    let elapsedRealtimeNanos = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)

    return RangingSample(
      deviceId: deviceId,
      distanceMeters: distanceMeters,
      azimuthDegrees: azimuthDegrees,
      elevationDegrees: elevationDegrees,
      elapsedRealtimeNanos: elapsedRealtimeNanos
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      distanceMeters,
      azimuthDegrees,
      elevationDegrees,
      elapsedRealtimeNanos,
    ]
  }
}

/// FiRa session parameters returned by an [AccessoryAdapter] handshake.
///
/// The plugin uses these to open a Jetpack `controllerSessionScope()` (or
/// `controleeSessionScope()` if [roleIsController] is false) and start a
/// FiRa ranging session. Android-only in v1.
///
/// Generated class from Pigeon that represents data sent in messages.
struct FiraSessionParams {
  /// FiRa session id (32-bit). Both ends must agree.
  var sessionId: Int64
  /// FiRa channel number (5, 9, etc.).
  var channel: Int64
  /// FiRa preamble code index (BPRF set: 9–12).
  var preambleIndex: Int64
  /// Slot duration in ms. Jetpack accepts {1, 2}; android.ranging on
  /// Android 16+ accepts arbitrary ints. Slot duration ≥ 3 ms requires
  /// Android 16+; earlier OS versions fail the handshake with a clear
  /// "slot duration unsupported on this Android version" message.
  var slotDurationMs: Int64
  /// Slots per ranging round (FiRa default 6 for `CONFIG_UNICAST_DS_TWR`).
  var slotsPerRangingRound: Int64
  /// Ranging interval in ms.
  var rangingIntervalMs: Int64
  /// 8-byte FiRa Static-STS sessionKeyInfo. Layout =
  /// `vendorId(2B) || stsIv(6B)` for `CONFIG_UNICAST_DS_TWR`.
  var sessionKeyInfo: FlutterStandardTypedData
  /// Peer's 2-byte short address, MSB-first (matches
  /// `androidx.core.uwb.UwbAddress` byte order).
  var peerShortAddress: FlutterStandardTypedData
  /// `true` when Android plays the controller (host) role; `false` when
  /// Android plays the controlee. v1 adapters always set this to `true`.
  var roleIsController: Bool
  /// Reserved for a future iOS adapter framework; ignored on Android.
  var appleShareableConfig: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> FiraSessionParams? {
    let sessionId = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let channel = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let preambleIndex = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let slotDurationMs = list[3] is Int64 ? list[3] as! Int64 : Int64(list[3] as! Int32)
    let slotsPerRangingRound = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let rangingIntervalMs = list[5] is Int64 ? list[5] as! Int64 : Int64(list[5] as! Int32)
    let sessionKeyInfo = list[6] as! FlutterStandardTypedData
    let peerShortAddress = list[7] as! FlutterStandardTypedData
    let roleIsController = list[8] as! Bool
    let appleShareableConfig: FlutterStandardTypedData? = nilOrValue(list[9])

    return FiraSessionParams(
      sessionId: sessionId,
      channel: channel,
      preambleIndex: preambleIndex,
      slotDurationMs: slotDurationMs,
      slotsPerRangingRound: slotsPerRangingRound,
      rangingIntervalMs: rangingIntervalMs,
      sessionKeyInfo: sessionKeyInfo,
      peerShortAddress: peerShortAddress,
      roleIsController: roleIsController,
      appleShareableConfig: appleShareableConfig
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      channel,
      preambleIndex,
      slotDurationMs,
      slotsPerRangingRound,
      rangingIntervalMs,
      sessionKeyInfo,
      peerShortAddress,
      roleIsController,
      appleShareableConfig,
    ]
  }
}

/// Native → Dart event during an accessory adapter handshake.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccessoryHandshakeEvent {
  var kind: AccessoryHandshakeEventKind
  var bytes: FlutterStandardTypedData? = nil
  var errorMessage: String? = nil

  static func fromList(_ list: [Any?]) -> AccessoryHandshakeEvent? {
    let kind = AccessoryHandshakeEventKind(rawValue: list[0] as! Int)!
    let bytes: FlutterStandardTypedData? = nilOrValue(list[1])
    let errorMessage: String? = nilOrValue(list[2])

    return AccessoryHandshakeEvent(
      kind: kind,
      bytes: bytes,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      kind.rawValue,
      bytes,
      errorMessage,
    ]
  }
}

private class UwbHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AccessoryProfile.fromList(self.readValue() as! [Any?])
      case 129:
        return DeviceCapabilities.fromList(self.readValue() as! [Any?])
      case 130:
        return FiraSessionParams.fromList(self.readValue() as! [Any?])
      case 131:
        return RangingOptions.fromList(self.readValue() as! [Any?])
      case 132:
        return TokenPayload.fromList(self.readValue() as! [Any?])
      case 133:
        return UwbDevice.fromList(self.readValue() as! [Any?])
      case 134:
        return UwbDevice.fromList(self.readValue() as! [Any?])
      case 135:
        return UwbReadiness.fromList(self.readValue() as! [Any?])
      case 136:
        return VoidResult.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class UwbHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AccessoryProfile {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? DeviceCapabilities {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? FiraSessionParams {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RangingOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? TokenPayload {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? UwbDevice {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? UwbDevice {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? UwbReadiness {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VoidResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UwbHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UwbHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UwbHostApiCodecWriter(data: data)
  }
}

class UwbHostApiCodec: FlutterStandardMessageCodec {
  static let shared = UwbHostApiCodec(readerWriter: UwbHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UwbHostApi {
  func startDiscovery(localName: String) throws -> VoidResult
  func stopDiscovery() throws -> VoidResult
  func getDiscovered() throws -> [UwbDevice]
  func acceptRequest(deviceId: String, myToken: TokenPayload) throws -> VoidResult
  func declineRequest(deviceId: String) throws -> VoidResult
  func registerAccessoryProfile(profile: AccessoryProfile) throws -> VoidResult
  func unregisterAccessoryProfile(serviceUuid: String) throws -> VoidResult
  func exchangeTokens(deviceId: String, myToken: TokenPayload, completion: @escaping (Result<TokenPayload, Error>) -> Void)
  func isUwbAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the platform-native OOB token to share with the peer.
  /// On Android the format is the 9-byte little-endian blob:
  ///   [0]   role (0=controller, 1=controlee)
  ///   [1..2] shortAddr (u16)
  ///   [3]   channel (u8, controller only)
  ///   [4]   preambleIndex (u8, controller only)
  ///   [5..8] sessionId (u32, controller only)
  /// On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
  func getLocalToken(role: UwbRole, completion: @escaping (Result<TokenPayload, Error>) -> Void)
  func startRanging(deviceId: String, options: RangingOptions, completion: @escaping (Result<VoidResult, Error>) -> Void)
  func stopRanging(completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Snapshot of the local UWB radio's capabilities. Returns the
  /// platform-specific profile (iOS-only fields are false on Android,
  /// Android-only fields are empty on iOS).
  func getDeviceCapabilities(completion: @escaping (Result<DeviceCapabilities, Error>) -> Void)
  /// One-shot check of everything the plugin needs to start ranging:
  /// UWB hardware, Bluetooth state, runtime permissions. The host app
  /// uses this to drive its onboarding flow before calling
  /// [startDiscovery] / [startRanging].
  func checkReadiness(completion: @escaping (Result<UwbReadiness, Error>) -> Void)
  /// Push the current set of vendor tags Dart has registered an
  /// [AccessoryAdapter] for. The Android dispatcher uses this to route
  /// `accessory:<vendorTag>` `startRanging` calls through the
  /// Dart-driven path; iOS throws `unsupported`.
  func setRegisteredAdapterTags(vendorTags: [String], completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Surface a Dart-supplied accessory device on the native discovered
  /// map so a subsequent [startRanging] resolves to a strategy. Used
  /// by built-in adapters (e.g. the static-pair Qorvo tile) and by
  /// custom adapters that synthesize devices without a real BLE scan
  /// hit. iOS throws `unsupported`.
  func surfaceAccessoryDevice(device: UwbDevice, completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Inverse of [surfaceAccessoryDevice]. Removes the synthetic device
  /// from the native discovered map. iOS throws `unsupported`.
  func unsurfaceAccessoryDevice(deviceId: String, completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Open the BLE handshake link for [deviceId] and start emitting
  /// [UwbFlutterApi.onAccessoryHandshakeEvent] events. The adapter's
  /// `handshake` callback runs on the Dart side and writes back via
  /// [accessoryProtocolWrite] / [completeAccessoryHandshake] /
  /// [failAccessoryHandshake]. Android-only.
  func beginAccessoryHandshake(deviceId: String, completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Adapter → accessory bytes. Goes to the matched profile's `rxUuid`
  /// characteristic on the open BLE GATT client. Android-only.
  func accessoryProtocolWrite(deviceId: String, bytes: FlutterStandardTypedData, completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Adapter delivers the FiRa params it negotiated; the plugin opens
  /// a `controllerSessionScope()` (or `controleeSessionScope()`) and
  /// starts the UWB session. Android-only.
  func completeAccessoryHandshake(deviceId: String, params: FiraSessionParams, completion: @escaping (Result<VoidResult, Error>) -> Void)
  /// Adapter signals a handshake failure; the plugin tears down the
  /// strategy and emits [UwbFlutterApi.onRangingError]. Android-only.
  func failAccessoryHandshake(deviceId: String, message: String, completion: @escaping (Result<VoidResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UwbHostApiSetup {
  /// The codec used by UwbHostApi.
  static var codec: FlutterStandardMessageCodec { UwbHostApiCodec.shared }
  /// Sets up an instance of `UwbHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UwbHostApi?) {
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startDiscovery", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localNameArg = args[0] as! String
        do {
          let result = try api.startDiscovery(localName: localNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopDiscovery", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.stopDiscovery()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let getDiscoveredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDiscovered", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiscoveredChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDiscovered()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDiscoveredChannel.setMessageHandler(nil)
    }
    let acceptRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.acceptRequest", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acceptRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let myTokenArg = args[1] as! TokenPayload
        do {
          let result = try api.acceptRequest(deviceId: deviceIdArg, myToken: myTokenArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      acceptRequestChannel.setMessageHandler(nil)
    }
    let declineRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.declineRequest", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      declineRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          let result = try api.declineRequest(deviceId: deviceIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      declineRequestChannel.setMessageHandler(nil)
    }
    let registerAccessoryProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.registerAccessoryProfile", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerAccessoryProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let profileArg = args[0] as! AccessoryProfile
        do {
          let result = try api.registerAccessoryProfile(profile: profileArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerAccessoryProfileChannel.setMessageHandler(nil)
    }
    let unregisterAccessoryProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unregisterAccessoryProfile", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterAccessoryProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serviceUuidArg = args[0] as! String
        do {
          let result = try api.unregisterAccessoryProfile(serviceUuid: serviceUuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unregisterAccessoryProfileChannel.setMessageHandler(nil)
    }
    let exchangeTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.exchangeTokens", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exchangeTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let myTokenArg = args[1] as! TokenPayload
        api.exchangeTokens(deviceId: deviceIdArg, myToken: myTokenArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      exchangeTokensChannel.setMessageHandler(nil)
    }
    let isUwbAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.isUwbAvailable", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isUwbAvailableChannel.setMessageHandler { _, reply in
        api.isUwbAvailable() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      isUwbAvailableChannel.setMessageHandler(nil)
    }
    /// Returns the platform-native OOB token to share with the peer.
    /// On Android the format is the 9-byte little-endian blob:
    ///   [0]   role (0=controller, 1=controlee)
    ///   [1..2] shortAddr (u16)
    ///   [3]   channel (u8, controller only)
    ///   [4]   preambleIndex (u8, controller only)
    ///   [5..8] sessionId (u32, controller only)
    /// On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
    let getLocalTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getLocalToken", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocalTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let roleArg = UwbRole(rawValue: args[0] as! Int)!
        api.getLocalToken(role: roleArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getLocalTokenChannel.setMessageHandler(nil)
    }
    let startRangingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startRanging", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRangingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let optionsArg = args[1] as! RangingOptions
        api.startRanging(deviceId: deviceIdArg, options: optionsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      startRangingChannel.setMessageHandler(nil)
    }
    let stopRangingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopRanging", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRangingChannel.setMessageHandler { _, reply in
        api.stopRanging() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      stopRangingChannel.setMessageHandler(nil)
    }
    /// Snapshot of the local UWB radio's capabilities. Returns the
    /// platform-specific profile (iOS-only fields are false on Android,
    /// Android-only fields are empty on iOS).
    let getDeviceCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDeviceCapabilities", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceCapabilitiesChannel.setMessageHandler { _, reply in
        api.getDeviceCapabilities() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getDeviceCapabilitiesChannel.setMessageHandler(nil)
    }
    /// One-shot check of everything the plugin needs to start ranging:
    /// UWB hardware, Bluetooth state, runtime permissions. The host app
    /// uses this to drive its onboarding flow before calling
    /// [startDiscovery] / [startRanging].
    let checkReadinessChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.checkReadiness", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      checkReadinessChannel.setMessageHandler { _, reply in
        api.checkReadiness() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      checkReadinessChannel.setMessageHandler(nil)
    }
    /// Push the current set of vendor tags Dart has registered an
    /// [AccessoryAdapter] for. The Android dispatcher uses this to route
    /// `accessory:<vendorTag>` `startRanging` calls through the
    /// Dart-driven path; iOS throws `unsupported`.
    let setRegisteredAdapterTagsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.setRegisteredAdapterTags", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRegisteredAdapterTagsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vendorTagsArg = args[0] as! [String]
        api.setRegisteredAdapterTags(vendorTags: vendorTagsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      setRegisteredAdapterTagsChannel.setMessageHandler(nil)
    }
    /// Surface a Dart-supplied accessory device on the native discovered
    /// map so a subsequent [startRanging] resolves to a strategy. Used
    /// by built-in adapters (e.g. the static-pair Qorvo tile) and by
    /// custom adapters that synthesize devices without a real BLE scan
    /// hit. iOS throws `unsupported`.
    let surfaceAccessoryDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.surfaceAccessoryDevice", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      surfaceAccessoryDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceArg = args[0] as! UwbDevice
        api.surfaceAccessoryDevice(device: deviceArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      surfaceAccessoryDeviceChannel.setMessageHandler(nil)
    }
    /// Inverse of [surfaceAccessoryDevice]. Removes the synthetic device
    /// from the native discovered map. iOS throws `unsupported`.
    let unsurfaceAccessoryDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unsurfaceAccessoryDevice", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unsurfaceAccessoryDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.unsurfaceAccessoryDevice(deviceId: deviceIdArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      unsurfaceAccessoryDeviceChannel.setMessageHandler(nil)
    }
    /// Open the BLE handshake link for [deviceId] and start emitting
    /// [UwbFlutterApi.onAccessoryHandshakeEvent] events. The adapter's
    /// `handshake` callback runs on the Dart side and writes back via
    /// [accessoryProtocolWrite] / [completeAccessoryHandshake] /
    /// [failAccessoryHandshake]. Android-only.
    let beginAccessoryHandshakeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.beginAccessoryHandshake", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      beginAccessoryHandshakeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.beginAccessoryHandshake(deviceId: deviceIdArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      beginAccessoryHandshakeChannel.setMessageHandler(nil)
    }
    /// Adapter → accessory bytes. Goes to the matched profile's `rxUuid`
    /// characteristic on the open BLE GATT client. Android-only.
    let accessoryProtocolWriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.accessoryProtocolWrite", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      accessoryProtocolWriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let bytesArg = args[1] as! FlutterStandardTypedData
        api.accessoryProtocolWrite(deviceId: deviceIdArg, bytes: bytesArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      accessoryProtocolWriteChannel.setMessageHandler(nil)
    }
    /// Adapter delivers the FiRa params it negotiated; the plugin opens
    /// a `controllerSessionScope()` (or `controleeSessionScope()`) and
    /// starts the UWB session. Android-only.
    let completeAccessoryHandshakeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.completeAccessoryHandshake", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      completeAccessoryHandshakeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let paramsArg = args[1] as! FiraSessionParams
        api.completeAccessoryHandshake(deviceId: deviceIdArg, params: paramsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      completeAccessoryHandshakeChannel.setMessageHandler(nil)
    }
    /// Adapter signals a handshake failure; the plugin tears down the
    /// strategy and emits [UwbFlutterApi.onRangingError]. Android-only.
    let failAccessoryHandshakeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.failAccessoryHandshake", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      failAccessoryHandshakeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let messageArg = args[1] as! String
        api.failAccessoryHandshake(deviceId: deviceIdArg, message: messageArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      failAccessoryHandshakeChannel.setMessageHandler(nil)
    }
  }
}
private class UwbFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AccessoryHandshakeEvent.fromList(self.readValue() as! [Any?])
      case 129:
        return RangingError.fromList(self.readValue() as! [Any?])
      case 130:
        return RangingSample.fromList(self.readValue() as! [Any?])
      case 131:
        return TokenPayload.fromList(self.readValue() as! [Any?])
      case 132:
        return UwbDevice.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class UwbFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AccessoryHandshakeEvent {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? RangingError {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? RangingSample {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? TokenPayload {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? UwbDevice {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UwbFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UwbFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UwbFlutterApiCodecWriter(data: data)
  }
}

class UwbFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = UwbFlutterApiCodec(readerWriter: UwbFlutterApiCodecReaderWriter())
}

/// Callbacks from the host platform up to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol UwbFlutterApiProtocol {
  func onDeviceFound(device deviceArg: UwbDevice, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onDeviceLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onRangingSample(sample sampleArg: RangingSample, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onPeerLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onRangingError(deviceId deviceIdArg: String, error errorArg: RangingError, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onIncomingRequest(device deviceArg: UwbDevice, peerToken peerTokenArg: TokenPayload, completion: @escaping (Result<Void, FlutterError>) -> Void)
  /// Native → Dart events during an accessory adapter handshake. Routed
  /// to the `_AdapterRunner` Dart-side which fans them into the right
  /// adapter's `AccessoryConnection`. Android-only.
  func onAccessoryHandshakeEvent(deviceId deviceIdArg: String, event eventArg: AccessoryHandshakeEvent, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class UwbFlutterApi: UwbFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return UwbFlutterApiCodec.shared
  }
  func onDeviceFound(device deviceArg: UwbDevice, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDeviceLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRangingSample(sample sampleArg: RangingSample, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sampleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPeerLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRangingError(deviceId deviceIdArg: String, error errorArg: RangingError, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onIncomingRequest(device deviceArg: UwbDevice, peerToken peerTokenArg: TokenPayload, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg, peerTokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Native → Dart events during an accessory adapter handshake. Routed
  /// to the `_AdapterRunner` Dart-side which fans them into the right
  /// adapter's `AccessoryConnection`. Android-only.
  func onAccessoryHandshakeEvent(deviceId deviceIdArg: String, event eventArg: AccessoryHandshakeEvent, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onAccessoryHandshakeEvent"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
}
