// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Role for an OOB token. Encoded into byte 0 of the token blob.
enum UwbRole: Int {
  case controller = 0
  case controlee = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct UwbDevice {
  var id: String? = nil
  var name: String? = nil
  var platform: String? = nil

  static func fromList(_ list: [Any?]) -> UwbDevice? {
    let id: String? = nilOrValue(list[0])
    let name: String? = nilOrValue(list[1])
    let platform: String? = nilOrValue(list[2])

    return UwbDevice(
      id: id,
      name: name,
      platform: platform
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      platform,
    ]
  }
}

/// BLE service + characteristic triplet describing an accessory.
///
/// `serviceUuid` is the GATT service the iPhone/Android scans for and
/// connects to. `rxUuid` is the characteristic the host writes to (the
/// accessory's "Rx"); `txUuid` is the one the accessory pushes via
/// notifications (its "Tx").
///
/// `vendorTag` is appended to `UwbDevice.platform` as `accessory:<tag>` so
/// the Dart side can filter; pass `null` for the built-in Apple-FiRa
/// handling (`UwbDevice.platform == "accessory"`).
///
/// Generated class from Pigeon that represents data sent in messages.
struct AccessoryProfile {
  var serviceUuid: String? = nil
  var rxUuid: String? = nil
  var txUuid: String? = nil
  var vendorTag: String? = nil

  static func fromList(_ list: [Any?]) -> AccessoryProfile? {
    let serviceUuid: String? = nilOrValue(list[0])
    let rxUuid: String? = nilOrValue(list[1])
    let txUuid: String? = nilOrValue(list[2])
    let vendorTag: String? = nilOrValue(list[3])

    return AccessoryProfile(
      serviceUuid: serviceUuid,
      rxUuid: rxUuid,
      txUuid: txUuid,
      vendorTag: vendorTag
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      rxUuid,
      txUuid,
      vendorTag,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TokenPayload {
  var bytes: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> TokenPayload? {
    let bytes: FlutterStandardTypedData? = nilOrValue(list[0])

    return TokenPayload(
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      bytes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VoidResult {
  var ok: Bool? = nil
  var error: String? = nil

  static func fromList(_ list: [Any?]) -> VoidResult? {
    let ok: Bool? = nilOrValue(list[0])
    let error: String? = nilOrValue(list[1])

    return VoidResult(
      ok: ok,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      ok,
      error,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RangingSample {
  var deviceId: String? = nil
  var distanceMeters: Double? = nil
  var azimuthDegrees: Double? = nil
  var elevationDegrees: Double? = nil
  var elapsedRealtimeNanos: Int64? = nil

  static func fromList(_ list: [Any?]) -> RangingSample? {
    let deviceId: String? = nilOrValue(list[0])
    let distanceMeters: Double? = nilOrValue(list[1])
    let azimuthDegrees: Double? = nilOrValue(list[2])
    let elevationDegrees: Double? = nilOrValue(list[3])
    let elapsedRealtimeNanos: Int64? = isNullish(list[4]) ? nil : (list[4] is Int64? ? list[4] as! Int64? : Int64(list[4] as! Int32))

    return RangingSample(
      deviceId: deviceId,
      distanceMeters: distanceMeters,
      azimuthDegrees: azimuthDegrees,
      elevationDegrees: elevationDegrees,
      elapsedRealtimeNanos: elapsedRealtimeNanos
    )
  }
  func toList() -> [Any?] {
    return [
      deviceId,
      distanceMeters,
      azimuthDegrees,
      elevationDegrees,
      elapsedRealtimeNanos,
    ]
  }
}

private class UwbHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return AccessoryProfile.fromList(self.readValue() as! [Any?])
      case 129:
        return TokenPayload.fromList(self.readValue() as! [Any?])
      case 130:
        return UwbDevice.fromList(self.readValue() as! [Any?])
      case 131:
        return VoidResult.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class UwbHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? AccessoryProfile {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? TokenPayload {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? UwbDevice {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? VoidResult {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UwbHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UwbHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UwbHostApiCodecWriter(data: data)
  }
}

class UwbHostApiCodec: FlutterStandardMessageCodec {
  static let shared = UwbHostApiCodec(readerWriter: UwbHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol UwbHostApi {
  func startDiscovery(localName: String) throws -> VoidResult
  func stopDiscovery() throws -> VoidResult
  func getDiscovered() throws -> [UwbDevice]
  func acceptRequest(deviceId: String, myToken: TokenPayload) throws -> VoidResult
  func declineRequest(deviceId: String) throws -> VoidResult
  func registerAccessoryProfile(profile: AccessoryProfile) throws -> VoidResult
  func unregisterAccessoryProfile(serviceUuid: String) throws -> VoidResult
  func exchangeTokens(deviceId: String, myToken: TokenPayload, completion: @escaping (Result<TokenPayload, Error>) -> Void)
  func isUwbAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Returns the platform-native OOB token to share with the peer.
  /// On Android the format is the 9-byte little-endian blob:
  ///   [0]   role (0=controller, 1=controlee)
  ///   [1..2] shortAddr (u16)
  ///   [3]   channel (u8, controller only)
  ///   [4]   preambleIndex (u8, controller only)
  ///   [5..8] sessionId (u32, controller only)
  /// On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
  func getLocalToken(role: UwbRole, completion: @escaping (Result<TokenPayload, Error>) -> Void)
  func startRanging(deviceId: String, completion: @escaping (Result<VoidResult, Error>) -> Void)
  func stopRanging(completion: @escaping (Result<VoidResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class UwbHostApiSetup {
  /// The codec used by UwbHostApi.
  static var codec: FlutterStandardMessageCodec { UwbHostApiCodec.shared }
  /// Sets up an instance of `UwbHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: UwbHostApi?) {
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startDiscovery", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let localNameArg = args[0] as! String
        do {
          let result = try api.startDiscovery(localName: localNameArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopDiscovery", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.stopDiscovery()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let getDiscoveredChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDiscovered", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDiscoveredChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDiscovered()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDiscoveredChannel.setMessageHandler(nil)
    }
    let acceptRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.acceptRequest", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acceptRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let myTokenArg = args[1] as! TokenPayload
        do {
          let result = try api.acceptRequest(deviceId: deviceIdArg, myToken: myTokenArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      acceptRequestChannel.setMessageHandler(nil)
    }
    let declineRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.declineRequest", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      declineRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        do {
          let result = try api.declineRequest(deviceId: deviceIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      declineRequestChannel.setMessageHandler(nil)
    }
    let registerAccessoryProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.registerAccessoryProfile", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerAccessoryProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let profileArg = args[0] as! AccessoryProfile
        do {
          let result = try api.registerAccessoryProfile(profile: profileArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerAccessoryProfileChannel.setMessageHandler(nil)
    }
    let unregisterAccessoryProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unregisterAccessoryProfile", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterAccessoryProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let serviceUuidArg = args[0] as! String
        do {
          let result = try api.unregisterAccessoryProfile(serviceUuid: serviceUuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unregisterAccessoryProfileChannel.setMessageHandler(nil)
    }
    let exchangeTokensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.exchangeTokens", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      exchangeTokensChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        let myTokenArg = args[1] as! TokenPayload
        api.exchangeTokens(deviceId: deviceIdArg, myToken: myTokenArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      exchangeTokensChannel.setMessageHandler(nil)
    }
    let isUwbAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.isUwbAvailable", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isUwbAvailableChannel.setMessageHandler { _, reply in
        api.isUwbAvailable() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      isUwbAvailableChannel.setMessageHandler(nil)
    }
    /// Returns the platform-native OOB token to share with the peer.
    /// On Android the format is the 9-byte little-endian blob:
    ///   [0]   role (0=controller, 1=controlee)
    ///   [1..2] shortAddr (u16)
    ///   [3]   channel (u8, controller only)
    ///   [4]   preambleIndex (u8, controller only)
    ///   [5..8] sessionId (u32, controller only)
    /// On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
    let getLocalTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getLocalToken", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocalTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let roleArg = UwbRole(rawValue: args[0] as! Int)!
        api.getLocalToken(role: roleArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getLocalTokenChannel.setMessageHandler(nil)
    }
    let startRangingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startRanging", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startRangingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceIdArg = args[0] as! String
        api.startRanging(deviceId: deviceIdArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      startRangingChannel.setMessageHandler(nil)
    }
    let stopRangingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopRanging", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopRangingChannel.setMessageHandler { _, reply in
        api.stopRanging() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      stopRangingChannel.setMessageHandler(nil)
    }
  }
}
private class UwbFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return RangingSample.fromList(self.readValue() as! [Any?])
      case 129:
        return TokenPayload.fromList(self.readValue() as! [Any?])
      case 130:
        return UwbDevice.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class UwbFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? RangingSample {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? TokenPayload {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? UwbDevice {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class UwbFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return UwbFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return UwbFlutterApiCodecWriter(data: data)
  }
}

class UwbFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = UwbFlutterApiCodec(readerWriter: UwbFlutterApiCodecReaderWriter())
}

/// Callbacks from the host platform up to Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol UwbFlutterApiProtocol {
  func onDeviceFound(device deviceArg: UwbDevice, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onDeviceLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onRangingSample(sample sampleArg: RangingSample, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onPeerLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onRangingError(deviceId deviceIdArg: String, message messageArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onIncomingRequest(device deviceArg: UwbDevice, peerToken peerTokenArg: TokenPayload, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class UwbFlutterApi: UwbFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return UwbFlutterApiCodec.shared
  }
  func onDeviceFound(device deviceArg: UwbDevice, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDeviceLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRangingSample(sample sampleArg: RangingSample, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([sampleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPeerLost(deviceId deviceIdArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRangingError(deviceId deviceIdArg: String, message messageArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceIdArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onIncomingRequest(device deviceArg: UwbDevice, peerToken peerTokenArg: TokenPayload, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg, peerTokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName:channelName)))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else {
        completion(.success(Void()))
      }
    }
  }
}
