// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.ahmedhamdan.flutter_uwb

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Role for an OOB token. Encoded into byte 0 of the token blob. */
enum class UwbRole(val raw: Int) {
  CONTROLLER(0),
  CONTROLEE(1);

  companion object {
    fun ofRaw(raw: Int): UwbRole? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Stable error code surface for the [RangingError] raised from a UWB
 * session. The native sides map their respective platform errors
 * (`RangingResultFailure.reasonCode` / `STATE_CHANGE_REASON_*` on
 * Android; `NIError.Code` / `CBError.Code` on iOS) onto these values.
 */
enum class UwbErrorCode(val raw: Int) {
  /**
   * The OS denied a permission the plugin needs (Bluetooth scan/connect/
   * advertise, fine location on Android < 12, Nearby Interaction or camera
   * usage on iOS). Recover by requesting the missing permission and
   * retrying — the rest of the plugin state is unchanged.
   */
  PERMISSIONDENIED(0),
  /**
   * The UWB radio is present but disabled or unavailable (airplane mode,
   * hardware fault, OS-level toggle). Surface a "turn UWB on" prompt to
   * the user; nothing the plugin can do programmatically.
   */
  UWBDISABLED(1),
  /**
   * The peer dropped during ranging (out of range, BLE link lost, app on
   * the other side closed). The session is torn down before this fires;
   * the only recovery is rediscovery and re-pair.
   */
  PEERLOST(2),
  /**
   * UWB use is restricted in the device's current region (Russia,
   * Indonesia, and a small number of other jurisdictions disable the
   * radio entirely). Not user-recoverable; surface a region-restriction
   * notice.
   */
  REGIONALRESTRICTION(3),
  /**
   * The platform refused to start the UWB session (invalid token,
   * channel/preamble mismatch, unsupported config). Usually indicates the
   * peers disagreed on session parameters; re-pair before retrying.
   */
  SESSIONINITFAILED(4),
  /**
   * The OOB transport (BLE GATT) failed during a critical exchange —
   * connection drop mid-handshake, characteristic write failure, GATT
   * timeout. Retry the operation; if it persists, BLE on one side is in
   * a bad state.
   */
  TRANSPORTERROR(5),
  /**
   * Catch-all for platform errors the plugin couldn't classify. The
   * `message` field on [RangingError] / [UwbException] carries the
   * underlying platform string for debugging.
   */
  UNKNOWN(6);

  companion object {
    fun ofRaw(raw: Int): UwbErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Discriminator for [AccessoryHandshakeEvent.kind].
 *
 * Pigeon doesn't support sealed unions, so [AccessoryHandshakeEvent] is
 * a flat struct with a [kind] code and optional [bytes]/[errorMessage]
 * fields populated per kind.
 */
enum class AccessoryHandshakeEventKind(val raw: Int) {
  /**
   * BLE connection ready, notifications subscribed. The adapter's
   * `handshake` callback is dispatched right after this event.
   */
  CONNECTED(0),
  /**
   * Inbound bytes from the accessory's notify characteristic.
   * [AccessoryHandshakeEvent.bytes] carries the frame.
   */
  NOTIFYBYTES(1),
  /**
   * Transport-level error (write failed, GATT timeout, etc.).
   * [AccessoryHandshakeEvent.errorMessage] carries the platform message.
   */
  TRANSPORTERROR(2),
  /**
   * Peer disconnected. The adapter's pending Future fails with a
   * transport error.
   */
  DISCONNECTED(3),
  /**
   * `stopRanging` was called while the adapter was still running.
   * The adapter should cancel its work and return.
   */
  STOPREQUESTED(4);

  companion object {
    fun ofRaw(raw: Int): AccessoryHandshakeEventKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UwbDevice (
  val id: String,
  val name: String,
  val platform: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): UwbDevice {
      val id = list[0] as String
      val name = list[1] as String
      val platform = list[2] as String
      return UwbDevice(id, name, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      platform,
    )
  }
}

/**
 * BLE service + characteristic triplet describing an accessory.
 *
 * `serviceUuid` is the GATT service the iPhone/Android scans for and
 * connects to. `rxUuid` is the characteristic the host writes to (the
 * accessory's "Rx"); `txUuid` is the one the accessory pushes via
 * notifications (its "Tx").
 *
 * `vendorTag` is appended to `UwbDevice.platform` as `accessory:<tag>` so
 * the Dart side can filter; pass `null` for the built-in Apple-FiRa
 * handling (`UwbDevice.platform == "accessory"`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccessoryProfile (
  val serviceUuid: String,
  val rxUuid: String,
  val txUuid: String,
  val vendorTag: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): AccessoryProfile {
      val serviceUuid = list[0] as String
      val rxUuid = list[1] as String
      val txUuid = list[2] as String
      val vendorTag = list[3] as String?
      return AccessoryProfile(serviceUuid, rxUuid, txUuid, vendorTag)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      serviceUuid,
      rxUuid,
      txUuid,
      vendorTag,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenPayload (
  val bytes: ByteArray

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TokenPayload {
      val bytes = list[0] as ByteArray
      return TokenPayload(bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      bytes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoidResult (
  val ok: Boolean,
  val error: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VoidResult {
      val ok = list[0] as Boolean
      val error = list[1] as String?
      return VoidResult(ok, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      ok,
      error,
    )
  }
}

/**
 * Error raised from a UWB session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RangingError (
  val code: UwbErrorCode,
  val message: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingError {
      val code = UwbErrorCode.ofRaw(list[0] as Int)!!
      val message = list[1] as String
      return RangingError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      code.raw,
      message,
    )
  }
}

/**
 * Options modulating a ranging session. iOS-only flags are no-ops on
 * Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RangingOptions (
  /**
   * iOS only. Enables `NINearbyPeerConfiguration.isCameraAssistanceEnabled`.
   * Requires `NSCameraUsageDescription` in the host app's Info.plist.
   */
  val cameraAssist: Boolean,
  /**
   * iOS 17.4+ accessory only. Enables
   * `NINearbyAccessoryConfiguration.isExtendedDistanceMeasurementEnabled`.
   */
  val extendedDistance: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingOptions {
      val cameraAssist = list[0] as Boolean
      val extendedDistance = list[1] as Boolean
      return RangingOptions(cameraAssist, extendedDistance)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      cameraAssist,
      extendedDistance,
    )
  }
}

/**
 * What the local UWB radio supports. Some fields are platform-specific:
 * the iOS-only flags are always `false` on Android, and the Android-only
 * ranging-stack details (channels, config IDs, AoA, min interval) are
 * always empty / zero on iOS.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceCapabilities (
  val supportsPreciseDistance: Boolean,
  val supportsDirection: Boolean,
  val supportsCameraAssist: Boolean,
  val supportsExtendedDistance: Boolean,
  val supportedChannels: List<Long?>,
  val supportedConfigIds: List<Long?>,
  val minRangingIntervalMs: Long? = null,
  val supportsAoa: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeviceCapabilities {
      val supportsPreciseDistance = list[0] as Boolean
      val supportsDirection = list[1] as Boolean
      val supportsCameraAssist = list[2] as Boolean
      val supportsExtendedDistance = list[3] as Boolean
      val supportedChannels = list[4] as List<Long?>
      val supportedConfigIds = list[5] as List<Long?>
      val minRangingIntervalMs = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val supportsAoa = list[7] as Boolean
      return DeviceCapabilities(supportsPreciseDistance, supportsDirection, supportsCameraAssist, supportsExtendedDistance, supportedChannels, supportedConfigIds, minRangingIntervalMs, supportsAoa)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      supportsPreciseDistance,
      supportsDirection,
      supportsCameraAssist,
      supportsExtendedDistance,
      supportedChannels,
      supportedConfigIds,
      minRangingIntervalMs,
      supportsAoa,
    )
  }
}

/**
 * Snapshot of everything the plugin needs to start ranging.
 *
 * Returned by [UwbHostApi.checkReadiness]. The host app should branch
 * on each field and surface the appropriate UI:
 *
 * ```dart
 * final r = await uwb.checkReadiness();
 * if (!r.bluetoothEnabled) promptEnableBluetooth();
 * else if (!r.permissionsGranted) requestPermissions(r.missingPermissions);
 * else if (!r.uwbAvailable) showUnsupportedScreen();
 * else readyToRange();
 * ```
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UwbReadiness (
  /**
   * `true` if the device has a UWB radio and the OS allows ranging.
   * Mirrors [UwbHostApi.isUwbAvailable] — false on the iOS simulator and
   * on devices without UWB hardware.
   */
  val uwbAvailable: Boolean,
  /**
   * `true` if the system Bluetooth radio is powered on. Required for
   * OOB discovery / pairing on both platforms.
   */
  val bluetoothEnabled: Boolean,
  /**
   * `true` if every runtime permission the plugin needs has been
   * granted. Always `true` on iOS — iOS does not expose a programmatic
   * pre-check for `NSBluetoothAlwaysUsageDescription` /
   * `NSNearbyInteractionUsageDescription`; the OS prompts on first use.
   */
  val permissionsGranted: Boolean,
  /**
   * Android permission identifiers (`android.permission.*`) the plugin
   * needs but the user has not granted yet. Empty on iOS. Pass these
   * directly to your permission package — for example with
   * `permission_handler`:
   *
   * ```dart
   * final perms = r.missingPermissions
   *     .map(Permission.byValue)
   *     .toList();
   * await perms.request();
   * ```
   */
  val missingPermissions: List<String?>

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): UwbReadiness {
      val uwbAvailable = list[0] as Boolean
      val bluetoothEnabled = list[1] as Boolean
      val permissionsGranted = list[2] as Boolean
      val missingPermissions = list[3] as List<String?>
      return UwbReadiness(uwbAvailable, bluetoothEnabled, permissionsGranted, missingPermissions)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      uwbAvailable,
      bluetoothEnabled,
      permissionsGranted,
      missingPermissions,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RangingSample (
  val deviceId: String,
  val distanceMeters: Double,
  val azimuthDegrees: Double? = null,
  val elevationDegrees: Double? = null,
  val elapsedRealtimeNanos: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingSample {
      val deviceId = list[0] as String
      val distanceMeters = list[1] as Double
      val azimuthDegrees = list[2] as Double?
      val elevationDegrees = list[3] as Double?
      val elapsedRealtimeNanos = list[4].let { if (it is Int) it.toLong() else it as Long }
      return RangingSample(deviceId, distanceMeters, azimuthDegrees, elevationDegrees, elapsedRealtimeNanos)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      deviceId,
      distanceMeters,
      azimuthDegrees,
      elevationDegrees,
      elapsedRealtimeNanos,
    )
  }
}

/**
 * FiRa session parameters returned by an [AccessoryAdapter] handshake.
 *
 * The plugin uses these to open a Jetpack `controllerSessionScope()` (or
 * `controleeSessionScope()` if [roleIsController] is false) and start a
 * FiRa ranging session. Android-only in v1.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FiraSessionParams (
  /** FiRa session id (32-bit). Both ends must agree. */
  val sessionId: Long,
  /** FiRa channel number (5, 9, etc.). */
  val channel: Long,
  /** FiRa preamble code index (BPRF set: 9–12). */
  val preambleIndex: Long,
  /**
   * Slot duration in ms. Jetpack accepts {1, 2}; android.ranging on
   * Android 16+ accepts arbitrary ints. Slot duration ≥ 3 ms requires
   * Android 16+; earlier OS versions fail the handshake with a clear
   * "slot duration unsupported on this Android version" message.
   */
  val slotDurationMs: Long,
  /** Slots per ranging round (FiRa default 6 for `CONFIG_UNICAST_DS_TWR`). */
  val slotsPerRangingRound: Long,
  /** Ranging interval in ms. */
  val rangingIntervalMs: Long,
  /**
   * 8-byte FiRa Static-STS sessionKeyInfo. Layout =
   * `vendorId(2B) || stsIv(6B)` for `CONFIG_UNICAST_DS_TWR`.
   */
  val sessionKeyInfo: ByteArray,
  /**
   * Peer's 2-byte short address, MSB-first (matches
   * `androidx.core.uwb.UwbAddress` byte order).
   */
  val peerShortAddress: ByteArray,
  /**
   * `true` when Android plays the controller (host) role; `false` when
   * Android plays the controlee. v1 adapters always set this to `true`.
   */
  val roleIsController: Boolean,
  /** Reserved for a future iOS adapter framework; ignored on Android. */
  val appleShareableConfig: ByteArray? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): FiraSessionParams {
      val sessionId = list[0].let { if (it is Int) it.toLong() else it as Long }
      val channel = list[1].let { if (it is Int) it.toLong() else it as Long }
      val preambleIndex = list[2].let { if (it is Int) it.toLong() else it as Long }
      val slotDurationMs = list[3].let { if (it is Int) it.toLong() else it as Long }
      val slotsPerRangingRound = list[4].let { if (it is Int) it.toLong() else it as Long }
      val rangingIntervalMs = list[5].let { if (it is Int) it.toLong() else it as Long }
      val sessionKeyInfo = list[6] as ByteArray
      val peerShortAddress = list[7] as ByteArray
      val roleIsController = list[8] as Boolean
      val appleShareableConfig = list[9] as ByteArray?
      return FiraSessionParams(sessionId, channel, preambleIndex, slotDurationMs, slotsPerRangingRound, rangingIntervalMs, sessionKeyInfo, peerShortAddress, roleIsController, appleShareableConfig)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sessionId,
      channel,
      preambleIndex,
      slotDurationMs,
      slotsPerRangingRound,
      rangingIntervalMs,
      sessionKeyInfo,
      peerShortAddress,
      roleIsController,
      appleShareableConfig,
    )
  }
}

/**
 * Native → Dart event during an accessory adapter handshake.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccessoryHandshakeEvent (
  val kind: AccessoryHandshakeEventKind,
  val bytes: ByteArray? = null,
  val errorMessage: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): AccessoryHandshakeEvent {
      val kind = AccessoryHandshakeEventKind.ofRaw(list[0] as Int)!!
      val bytes = list[1] as ByteArray?
      val errorMessage = list[2] as String?
      return AccessoryHandshakeEvent(kind, bytes, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      kind.raw,
      bytes,
      errorMessage,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object UwbHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccessoryProfile.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceCapabilities.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FiraSessionParams.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenPayload.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbDevice.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbDevice.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbReadiness.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoidResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccessoryProfile -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is DeviceCapabilities -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is FiraSessionParams -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is RangingOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is TokenPayload -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is UwbDevice -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is UwbDevice -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is UwbReadiness -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is VoidResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UwbHostApi {
  fun startDiscovery(localName: String): VoidResult
  fun stopDiscovery(): VoidResult
  fun getDiscovered(): List<UwbDevice>
  fun acceptRequest(deviceId: String, myToken: TokenPayload): VoidResult
  fun declineRequest(deviceId: String): VoidResult
  fun registerAccessoryProfile(profile: AccessoryProfile): VoidResult
  fun unregisterAccessoryProfile(serviceUuid: String): VoidResult
  fun exchangeTokens(deviceId: String, myToken: TokenPayload, callback: (Result<TokenPayload>) -> Unit)
  fun isUwbAvailable(callback: (Result<Boolean>) -> Unit)
  /**
   * Returns the platform-native OOB token to share with the peer.
   * On Android the format is the 9-byte little-endian blob:
   *   [0]   role (0=controller, 1=controlee)
   *   [1..2] shortAddr (u16)
   *   [3]   channel (u8, controller only)
   *   [4]   preambleIndex (u8, controller only)
   *   [5..8] sessionId (u32, controller only)
   * On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
   */
  fun getLocalToken(role: UwbRole, callback: (Result<TokenPayload>) -> Unit)
  fun startRanging(deviceId: String, options: RangingOptions, callback: (Result<VoidResult>) -> Unit)
  fun stopRanging(callback: (Result<VoidResult>) -> Unit)
  /**
   * Snapshot of the local UWB radio's capabilities. Returns the
   * platform-specific profile (iOS-only fields are false on Android,
   * Android-only fields are empty on iOS).
   */
  fun getDeviceCapabilities(callback: (Result<DeviceCapabilities>) -> Unit)
  /**
   * One-shot check of everything the plugin needs to start ranging:
   * UWB hardware, Bluetooth state, runtime permissions. The host app
   * uses this to drive its onboarding flow before calling
   * [startDiscovery] / [startRanging].
   */
  fun checkReadiness(callback: (Result<UwbReadiness>) -> Unit)
  /**
   * Push the current set of vendor tags Dart has registered an
   * [AccessoryAdapter] for. The Android dispatcher uses this to route
   * `accessory:<vendorTag>` `startRanging` calls through the
   * Dart-driven path; iOS throws `unsupported`.
   */
  fun setRegisteredAdapterTags(vendorTags: List<String>, callback: (Result<VoidResult>) -> Unit)
  /**
   * Surface a Dart-supplied accessory device on the native discovered
   * map so a subsequent [startRanging] resolves to a strategy. Used
   * by built-in adapters (e.g. the static-pair Qorvo tile) and by
   * custom adapters that synthesize devices without a real BLE scan
   * hit. iOS throws `unsupported`.
   */
  fun surfaceAccessoryDevice(device: UwbDevice, callback: (Result<VoidResult>) -> Unit)
  /**
   * Inverse of [surfaceAccessoryDevice]. Removes the synthetic device
   * from the native discovered map. iOS throws `unsupported`.
   */
  fun unsurfaceAccessoryDevice(deviceId: String, callback: (Result<VoidResult>) -> Unit)
  /**
   * Open the BLE handshake link for [deviceId] and start emitting
   * [UwbFlutterApi.onAccessoryHandshakeEvent] events. The adapter's
   * `handshake` callback runs on the Dart side and writes back via
   * [accessoryProtocolWrite] / [completeAccessoryHandshake] /
   * [failAccessoryHandshake]. Android-only.
   */
  fun beginAccessoryHandshake(deviceId: String, callback: (Result<VoidResult>) -> Unit)
  /**
   * Adapter → accessory bytes. Goes to the matched profile's `rxUuid`
   * characteristic on the open BLE GATT client. Android-only.
   */
  fun accessoryProtocolWrite(deviceId: String, bytes: ByteArray, callback: (Result<VoidResult>) -> Unit)
  /**
   * Adapter delivers the FiRa params it negotiated; the plugin opens
   * a `controllerSessionScope()` (or `controleeSessionScope()`) and
   * starts the UWB session. Android-only.
   */
  fun completeAccessoryHandshake(deviceId: String, params: FiraSessionParams, callback: (Result<VoidResult>) -> Unit)
  /**
   * Adapter signals a handshake failure; the plugin tears down the
   * strategy and emits [UwbFlutterApi.onRangingError]. Android-only.
   */
  fun failAccessoryHandshake(deviceId: String, message: String, callback: (Result<VoidResult>) -> Unit)

  companion object {
    /** The codec used by UwbHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      UwbHostApiCodec
    }
    /** Sets up an instance of `UwbHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: UwbHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startDiscovery", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localNameArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.startDiscovery(localNameArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopDiscovery", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.stopDiscovery())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDiscovered", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getDiscovered())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.acceptRequest", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val myTokenArg = args[1] as TokenPayload
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.acceptRequest(deviceIdArg, myTokenArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.declineRequest", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.declineRequest(deviceIdArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.registerAccessoryProfile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileArg = args[0] as AccessoryProfile
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.registerAccessoryProfile(profileArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unregisterAccessoryProfile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.unregisterAccessoryProfile(serviceUuidArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.exchangeTokens", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val myTokenArg = args[1] as TokenPayload
            api.exchangeTokens(deviceIdArg, myTokenArg) { result: Result<TokenPayload> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.isUwbAvailable", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isUwbAvailable() { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getLocalToken", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val roleArg = UwbRole.ofRaw(args[0] as Int)!!
            api.getLocalToken(roleArg) { result: Result<TokenPayload> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startRanging", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val optionsArg = args[1] as RangingOptions
            api.startRanging(deviceIdArg, optionsArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopRanging", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRanging() { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDeviceCapabilities", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceCapabilities() { result: Result<DeviceCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.checkReadiness", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.checkReadiness() { result: Result<UwbReadiness> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.setRegisteredAdapterTags", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val vendorTagsArg = args[0] as List<String>
            api.setRegisteredAdapterTags(vendorTagsArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.surfaceAccessoryDevice", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as UwbDevice
            api.surfaceAccessoryDevice(deviceArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unsurfaceAccessoryDevice", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.unsurfaceAccessoryDevice(deviceIdArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.beginAccessoryHandshake", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            api.beginAccessoryHandshake(deviceIdArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.accessoryProtocolWrite", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val bytesArg = args[1] as ByteArray
            api.accessoryProtocolWrite(deviceIdArg, bytesArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.completeAccessoryHandshake", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val paramsArg = args[1] as FiraSessionParams
            api.completeAccessoryHandshake(deviceIdArg, paramsArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.failAccessoryHandshake", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val messageArg = args[1] as String
            api.failAccessoryHandshake(deviceIdArg, messageArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object UwbFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccessoryHandshakeEvent.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingError.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingSample.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenPayload.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbDevice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccessoryHandshakeEvent -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is RangingError -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RangingSample -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TokenPayload -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is UwbDevice -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Callbacks from the host platform up to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
@Suppress("UNCHECKED_CAST")
class UwbFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by UwbFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      UwbFlutterApiCodec
    }
  }
  fun onDeviceFound(deviceArg: UwbDevice, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDeviceLost(deviceIdArg: String, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRangingSample(sampleArg: RangingSample, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sampleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPeerLost(deviceIdArg: String, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRangingError(deviceIdArg: String, errorArg: RangingError, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onIncomingRequest(deviceArg: UwbDevice, peerTokenArg: TokenPayload, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg, peerTokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /**
   * Native → Dart events during an accessory adapter handshake. Routed
   * to the `_AdapterRunner` Dart-side which fans them into the right
   * adapter's `AccessoryConnection`. Android-only.
   */
  fun onAccessoryHandshakeEvent(deviceIdArg: String, eventArg: AccessoryHandshakeEvent, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onAccessoryHandshakeEvent"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
