// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.ahmedhamdan.flutter_uwb

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Role for an OOB token. Encoded into byte 0 of the token blob. */
enum class UwbRole(val raw: Int) {
  CONTROLLER(0),
  CONTROLEE(1);

  companion object {
    fun ofRaw(raw: Int): UwbRole? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Stable error code surface for the [RangingError] raised from a UWB
 * session. The native sides map their respective platform errors
 * (`RangingResultFailure.reasonCode` / `STATE_CHANGE_REASON_*` on
 * Android; `NIError.Code` / `CBError.Code` on iOS) onto these values.
 */
enum class UwbErrorCode(val raw: Int) {
  PERMISSIONDENIED(0),
  UWBDISABLED(1),
  PEERLOST(2),
  REGIONALRESTRICTION(3),
  SESSIONINITFAILED(4),
  TRANSPORTERROR(5),
  UNKNOWN(6);

  companion object {
    fun ofRaw(raw: Int): UwbErrorCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UwbDevice (
  val id: String,
  val name: String,
  val platform: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): UwbDevice {
      val id = list[0] as String
      val name = list[1] as String
      val platform = list[2] as String
      return UwbDevice(id, name, platform)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      id,
      name,
      platform,
    )
  }
}

/**
 * BLE service + characteristic triplet describing an accessory.
 *
 * `serviceUuid` is the GATT service the iPhone/Android scans for and
 * connects to. `rxUuid` is the characteristic the host writes to (the
 * accessory's "Rx"); `txUuid` is the one the accessory pushes via
 * notifications (its "Tx").
 *
 * `vendorTag` is appended to `UwbDevice.platform` as `accessory:<tag>` so
 * the Dart side can filter; pass `null` for the built-in Apple-FiRa
 * handling (`UwbDevice.platform == "accessory"`).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AccessoryProfile (
  val serviceUuid: String,
  val rxUuid: String,
  val txUuid: String,
  val vendorTag: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): AccessoryProfile {
      val serviceUuid = list[0] as String
      val rxUuid = list[1] as String
      val txUuid = list[2] as String
      val vendorTag = list[3] as String?
      return AccessoryProfile(serviceUuid, rxUuid, txUuid, vendorTag)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      serviceUuid,
      rxUuid,
      txUuid,
      vendorTag,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TokenPayload (
  val bytes: ByteArray

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): TokenPayload {
      val bytes = list[0] as ByteArray
      return TokenPayload(bytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      bytes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VoidResult (
  val ok: Boolean,
  val error: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): VoidResult {
      val ok = list[0] as Boolean
      val error = list[1] as String?
      return VoidResult(ok, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      ok,
      error,
    )
  }
}

/**
 * Error raised from a UWB session.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RangingError (
  val code: UwbErrorCode,
  val message: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingError {
      val code = UwbErrorCode.ofRaw(list[0] as Int)!!
      val message = list[1] as String
      return RangingError(code, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      code.raw,
      message,
    )
  }
}

/**
 * Options modulating a ranging session. iOS-only flags are no-ops on
 * Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RangingOptions (
  /**
   * iOS only. Enables `NINearbyPeerConfiguration.isCameraAssistanceEnabled`.
   * Requires `NSCameraUsageDescription` in the host app's Info.plist.
   */
  val cameraAssist: Boolean,
  /**
   * iOS 17.4+ accessory only. Enables
   * `NINearbyAccessoryConfiguration.isExtendedDistanceMeasurementEnabled`.
   */
  val extendedDistance: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingOptions {
      val cameraAssist = list[0] as Boolean
      val extendedDistance = list[1] as Boolean
      return RangingOptions(cameraAssist, extendedDistance)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      cameraAssist,
      extendedDistance,
    )
  }
}

/**
 * What the local UWB radio supports. Some fields are platform-specific:
 * the iOS-only flags are always `false` on Android, and the Android-only
 * ranging-stack details (channels, config IDs, AoA, min interval) are
 * always empty / zero on iOS.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeviceCapabilities (
  val supportsPreciseDistance: Boolean,
  val supportsDirection: Boolean,
  val supportsCameraAssist: Boolean,
  val supportsExtendedDistance: Boolean,
  val supportedChannels: List<Long?>,
  val supportedConfigIds: List<Long?>,
  val minRangingIntervalMs: Long? = null,
  val supportsAoa: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): DeviceCapabilities {
      val supportsPreciseDistance = list[0] as Boolean
      val supportsDirection = list[1] as Boolean
      val supportsCameraAssist = list[2] as Boolean
      val supportsExtendedDistance = list[3] as Boolean
      val supportedChannels = list[4] as List<Long?>
      val supportedConfigIds = list[5] as List<Long?>
      val minRangingIntervalMs = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val supportsAoa = list[7] as Boolean
      return DeviceCapabilities(supportsPreciseDistance, supportsDirection, supportsCameraAssist, supportsExtendedDistance, supportedChannels, supportedConfigIds, minRangingIntervalMs, supportsAoa)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      supportsPreciseDistance,
      supportsDirection,
      supportsCameraAssist,
      supportsExtendedDistance,
      supportedChannels,
      supportedConfigIds,
      minRangingIntervalMs,
      supportsAoa,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RangingSample (
  val deviceId: String,
  val distanceMeters: Double,
  val azimuthDegrees: Double? = null,
  val elevationDegrees: Double? = null,
  val elapsedRealtimeNanos: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): RangingSample {
      val deviceId = list[0] as String
      val distanceMeters = list[1] as Double
      val azimuthDegrees = list[2] as Double?
      val elevationDegrees = list[3] as Double?
      val elapsedRealtimeNanos = list[4].let { if (it is Int) it.toLong() else it as Long }
      return RangingSample(deviceId, distanceMeters, azimuthDegrees, elevationDegrees, elapsedRealtimeNanos)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      deviceId,
      distanceMeters,
      azimuthDegrees,
      elevationDegrees,
      elapsedRealtimeNanos,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object UwbHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AccessoryProfile.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeviceCapabilities.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingOptions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenPayload.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbDevice.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VoidResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AccessoryProfile -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is DeviceCapabilities -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RangingOptions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is TokenPayload -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is UwbDevice -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VoidResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UwbHostApi {
  fun startDiscovery(localName: String): VoidResult
  fun stopDiscovery(): VoidResult
  fun getDiscovered(): List<UwbDevice>
  fun acceptRequest(deviceId: String, myToken: TokenPayload): VoidResult
  fun declineRequest(deviceId: String): VoidResult
  fun registerAccessoryProfile(profile: AccessoryProfile): VoidResult
  fun unregisterAccessoryProfile(serviceUuid: String): VoidResult
  fun exchangeTokens(deviceId: String, myToken: TokenPayload, callback: (Result<TokenPayload>) -> Unit)
  fun isUwbAvailable(callback: (Result<Boolean>) -> Unit)
  /**
   * Returns the platform-native OOB token to share with the peer.
   * On Android the format is the 9-byte little-endian blob:
   *   [0]   role (0=controller, 1=controlee)
   *   [1..2] shortAddr (u16)
   *   [3]   channel (u8, controller only)
   *   [4]   preambleIndex (u8, controller only)
   *   [5..8] sessionId (u32, controller only)
   * On iOS the bytes are an `NSKeyedArchiver`-encoded `NIDiscoveryToken`.
   */
  fun getLocalToken(role: UwbRole, callback: (Result<TokenPayload>) -> Unit)
  fun startRanging(deviceId: String, options: RangingOptions, callback: (Result<VoidResult>) -> Unit)
  fun stopRanging(callback: (Result<VoidResult>) -> Unit)
  /**
   * Snapshot of the local UWB radio's capabilities. Returns the
   * platform-specific profile (iOS-only fields are false on Android,
   * Android-only fields are empty on iOS).
   */
  fun getDeviceCapabilities(callback: (Result<DeviceCapabilities>) -> Unit)

  companion object {
    /** The codec used by UwbHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      UwbHostApiCodec
    }
    /** Sets up an instance of `UwbHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: UwbHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startDiscovery", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val localNameArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.startDiscovery(localNameArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopDiscovery", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.stopDiscovery())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDiscovered", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.getDiscovered())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.acceptRequest", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val myTokenArg = args[1] as TokenPayload
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.acceptRequest(deviceIdArg, myTokenArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.declineRequest", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.declineRequest(deviceIdArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.registerAccessoryProfile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileArg = args[0] as AccessoryProfile
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.registerAccessoryProfile(profileArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.unregisterAccessoryProfile", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceUuidArg = args[0] as String
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.unregisterAccessoryProfile(serviceUuidArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.exchangeTokens", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val myTokenArg = args[1] as TokenPayload
            api.exchangeTokens(deviceIdArg, myTokenArg) { result: Result<TokenPayload> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.isUwbAvailable", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isUwbAvailable() { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getLocalToken", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val roleArg = UwbRole.ofRaw(args[0] as Int)!!
            api.getLocalToken(roleArg) { result: Result<TokenPayload> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.startRanging", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceIdArg = args[0] as String
            val optionsArg = args[1] as RangingOptions
            api.startRanging(deviceIdArg, optionsArg) { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.stopRanging", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopRanging() { result: Result<VoidResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_uwb.UwbHostApi.getDeviceCapabilities", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getDeviceCapabilities() { result: Result<DeviceCapabilities> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object UwbFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingError.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RangingSample.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TokenPayload.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UwbDevice.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is RangingError -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is RangingSample -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TokenPayload -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is UwbDevice -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * Callbacks from the host platform up to Dart.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
@Suppress("UNCHECKED_CAST")
class UwbFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by UwbFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      UwbFlutterApiCodec
    }
  }
  fun onDeviceFound(deviceArg: UwbDevice, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceFound"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onDeviceLost(deviceIdArg: String, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onDeviceLost"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRangingSample(sampleArg: RangingSample, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingSample"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(sampleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPeerLost(deviceIdArg: String, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onPeerLost"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRangingError(deviceIdArg: String, errorArg: RangingError, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onRangingError"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onIncomingRequest(deviceArg: UwbDevice, peerTokenArg: TokenPayload, callback: (Result<Unit>) -> Unit) {
    val channelName = "dev.flutter.pigeon.flutter_uwb.UwbFlutterApi.onIncomingRequest"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg, peerTokenArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
